sudo apt install -y sqlite
sudo apt install -y ansible
sudo apt install -y aspcud
sudo apt install -y fontconfig
sudo apt install -y gettext
sudo apt install -y pkg-config
sudo apt install -y gobject-introspection
sudo apt install -y autoconf
sudo apt install -y automake
sudo apt install -y xz
sudo apt install -y python3
sudo apt install -y python3-pip
sudo apt install -y python-pip
sudo apt install -y awscli
sudo apt install -y ghc
sudo apt install -y cabal-install
sudo apt install -y gmp
sudo apt install -y cmake
sudo apt install -y cppunit
sudo apt install -y dialog
sudo apt install -y direnv
sudo apt install -y dirmngr
sudo apt install -y exercism
sudo apt install -y fasd
sudo apt install -y flow
sudo apt install -y fortune
sudo apt install -y fzf
sudo apt install -y gcc
sudo apt install -y jpeg
sudo apt install -y git
sudo apt install -y icu4c
sudo apt install -y lua@5.1
sudo apt install -y lua
sudo apt install -y gnu-getopt
sudo apt install -y gnu-typist
sudo apt install -y gnutls
sudo apt install -y pinentry
sudo apt install -y gnupg, link: false
sudo apt install -y gnuplot
sudo apt install -y go
sudo apt install -y gpg-agent
sudo apt install -y gradle
sudo apt install -y grc
sudo apt install -y haskell-stack
sudo apt install -y hh
sudo apt install -y highlight
sudo apt install -y htop
sudo apt install -y httpie
sudo apt install -y hub
sudo apt install -y iftop
sudo apt install -y jemalloc
sudo apt install -y jq
sudo apt install -y jrnl
sudo apt install -y node
sudo apt install -y jsdoc3
sudo apt install -y luajit
sudo apt install -y lynx
sudo apt install -y maven
sudo apt install -y mhash
sudo apt install -y mcrypt
sudo apt install -y mongodb
sudo apt install -y mycli
sudo apt install -y mysql, restart_service: true
sudo apt install -y ncurses
sudo apt install -y neovim
sudo apt install -y ngrep
sudo apt install -y nmap
sudo apt install -y numpy, link: false
sudo apt install -y nvm
sudo apt install -y tree
sudo apt install -y pass
sudo apt install -y pcre2
sudo apt install -y perl
sudo apt install -y pgcli
sudo apt install -y ponysay
sudo apt install -y postgresql, restart_service: true
sudo apt install -y postgresql
sudo apt install -y r
sudo apt install -y ranger
sudo apt install -y reattach-to-user-namespace
sudo apt install -y sbcl
sudo apt install -y sox
sudo apt install -y ssh-copy-id
sudo apt install -y task
sudo apt install -y tcptraceroute
sudo apt install -y the_silver_searcher
sudo apt install -y tig
sudo apt install -y tmux
sudo apt install -y typespeed
sudo apt install -y unar
sudo apt install -y unixodbc
sudo apt install -y utf8proc
sudo apt install -y w3m
sudo apt install -y watch
sudo apt install -y watchman
sudo apt install -y wget
sudo apt install -y z
sudo apt install -y mericurial
sudo apt install -y mercurial
sudo apt install -y vim-gtk3
sudo apt install -y gnome-shell-pomodoro
