sudo apt install sqlite
sudo apt install ansible
sudo apt install aspcud
sudo apt install fontconfig
sudo apt install gettext
sudo apt install pkg-config
sudo apt install gobject-introspection
sudo apt install autoconf
sudo apt install automake
sudo apt install xz
sudo apt install python3
sudo apt install awscli
sudo apt install ghc
sudo apt install cabal-install
sudo apt install gmp
sudo apt install cmake
sudo apt install cppunit
sudo apt install dialog
sudo apt install direnv
sudo apt install dirmngr
sudo apt install exercism
sudo apt install fasd
sudo apt install flow
sudo apt install fortune
sudo apt install fzf
sudo apt install gcc
sudo apt install jpeg
sudo apt install git
sudo apt install icu4c
sudo apt install lua@5.1
sudo apt install lua
sudo apt install gnu-getopt
sudo apt install gnu-typist
sudo apt install gnutls
sudo apt install pinentry
sudo apt install gnupg, link: false
sudo apt install gnuplot
sudo apt install go
sudo apt install gpg-agent
sudo apt install gradle
sudo apt install grc
sudo apt install haskell-stack
sudo apt install hh
sudo apt install highlight
sudo apt install htop
sudo apt install httpie
sudo apt install hub
sudo apt install iftop
sudo apt install jemalloc
sudo apt install jq
sudo apt install jrnl
sudo apt install node
sudo apt install jsdoc3
sudo apt install luajit
sudo apt install lynx
sudo apt install maven
sudo apt install mhash
sudo apt install mcrypt
sudo apt install mongodb
sudo apt install mycli
sudo apt install mysql, restart_service: true
sudo apt install ncurses
sudo apt install neovim
sudo apt install ngrep
sudo apt install nmap
sudo apt install numpy, link: false
sudo apt install nvm
sudo apt install tree
sudo apt install pass
sudo apt install pcre2
sudo apt install perl
sudo apt install pgcli
sudo apt install ponysay
sudo apt install postgresql, restart_service: true
sudo apt install postgresql
sudo apt install r
sudo apt install ranger
sudo apt install reattach-to-user-namespace
sudo apt install sbcl
sudo apt install sox
sudo apt install ssh-copy-id
sudo apt install task
sudo apt install tcptraceroute
sudo apt install the_silver_searcher
sudo apt install tig
sudo apt install tmux
sudo apt install typespeed
sudo apt install unar
sudo apt install unixodbc
sudo apt install utf8proc
sudo apt install w3m
sudo apt install watch
sudo apt install watchman
sudo apt install wget
sudo apt install z
sudo apt install mericurial
sudo apt-get build-dep vim
sudo apt-get install mercurial
sudo add-apt-repository ppa:jonathonf/vim
sudo apt update
sudo apt install vim

